#ifndef MY_PROJECT_ERROR_CODE_H_
#define MY_PROJECT_ERROR_CODE_H_

enum my_project_ErrorCode
{
	ERROR_NO,
	ERROR_INVALID_PARM = 3000,
	ERROR_EXTRACT_STOP,
	ERROR_FAILED_OPEN_FILE,
	ERROR_FILE_NOT_EXIST,
	ERROR_INVALID_THUMBS_DB_FILE,
	ERROR_FAILED_PARSE_THUMBS_DB_FILE,
	ERROR_INVALID_THUMBCACHE_DB_FILE,
	ERROR_FAILED_PARSE_THUMBCACHE_DB_FILE,
	ERROR_NOT_SUPPORT_SYSTEM,
	ERROR_NOT_INIT_DB_READER,
};

#endif // MY_PROJECT_ERROR_CODE_H_
